### ISSUE TITLE
Improve message in Installing CLI dialog 

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-tooling-feed#11]
VS shows following dialog when downloading Azure Function Core Tools 
![installingcli](https://user-images.githubusercontent.com/1874279/43102920-5ae8b382-8e81-11e8-86e5-17fa207528d9.png)

Message is confusing as it displays the CLI feed version and not the Azure Functions Core tools version.
Update message to: Downloading Azure Functions CLI tools

**Comment by pragnagopa** [comment]
cc: @soninaren

**Comment by soninaren** [comment]
This is fixed.
