### ISSUE TITLE
v3-preview missing from feed.json

### ISSUE THREAD

**Issue by zpittmansf** [Azure/azure-functions-tooling-feed#118]
The feed.json file is no longer getting v3-preview even though the tags and releases folders contain the appropriate content. I believe this is tied to my issue listed here https://github.com/Azure/azure-functions-host/issues/5145 where I cannot start my v3-preview project that was working yesterday.
C:\Users\[user]\AppData\Local\AzureFunctionsTools\feed.json

Help?

**Comment by mhoeger** [comment]
Closing, see resolution [here](https://github.com/Azure/azure-functions-host/issues/5145)
