### ISSUE TITLE
Add Java templates

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-tooling-feed#14]
Java templates are part for [azure-functions-maven-plugin](https://github.com/Microsoft/azure-maven-plugins/tree/develop/azure-functions-maven-plugin). This makes it difficult for version controlling Java templates for VS code.

**Comment by pragnagopa** [comment]
cc: @jdneo

**Comment by jdneo** [comment]
Hi @pragnagopa, please see the discussion here: https://github.com/Microsoft/vscode-azurefunctions/issues/486

**Comment by fabiocav** [comment]
@pragnagopa is this still relevant?

**Comment by pragnagopa** [comment]
Closing. If needed issue can be re-opened.
