### ISSUE TITLE
Change feed should expose node version

### ISSUE THREAD

**Issue by ahmelsayed** [Azure/azure-functions-tooling-feed#2]
_From @jeffhollan on June 13, 2018 21:23_

<creating here as placeholder while move to feed repo - delete whenever>

The change feed should expose the current version of node so tools like VS Code can utilize when creating / publishing apps

_Copied from original issue: Azure/azure-functions-core-tools#530_

**Comment by soninaren** [comment]
Fixed in this PR
https://github.com/Azure/azure-functions-tooling-feed/pull/6
