### ISSUE TITLE
Feed generator generates incorrect CLI link

### ISSUE THREAD

**Issue by ankitkumarr** [Azure/azure-functions-tooling-feed#232]
In `standaloneCli` entries, for x64 Windows, the generator includes the link for the `min` version of the CLI. This is inconsistent with other platforms. In the past we always included the full CLI links. I think this may have been a bug.

```json
standaloneCli": [
        {
          "OS": "Linux",
          "Architecture": "x64",
          "downloadLink": "https://functionscdn.azureedge.net/public/3.0.3233/Azure.Functions.Cli.linux-x64.3.0.3233.zip",
          "sha2": "4e34f8495c701b481292be70ca3abfc77a7449dccab58211298890657a743e19"
        },
        {
          "OS": "Windows",
          "Architecture": "x64",
          "downloadLink": "https://functionscdn.azureedge.net/public/3.0.3233/Azure.Functions.Cli.min.win-x64.3.0.3233.zip",
          "sha2": "be79e10b575a7111a33f2450a287b3ed9d6b2bd9d0702ee9297200fc569ac29d"
        },
        {
          "OS": "Windows",
          "Architecture": "x86",
          "downloadLink": "https://functionscdn.azureedge.net/public/3.0.3233/Azure.Functions.Cli.win-x86.3.0.3233.zip",
          "sha2": "9db43d54b20c918a9004bfaa3984f96613cfd7d61db4069126308bcacf26a9cf"
        }
      ]
```
Here, the link for Windows x64 is "..Azure.Functions.Cli.**min**.win-x64.3.0.3233.zip"

**Comment by ankitkumarr** [comment]
@yojagad or @soninaren, do either of you know if this was intentional or a bug?

**Comment by soninaren** [comment]
This is intentional.

**Comment by ankitkumarr** [comment]
@soninaren why?

**Comment by soninaren** [comment]
VS uses 64 bit CLI by default. "non-min" version of 64 bit CLI is 266 mb zip, and over 650 mb unzipped. This was talking as long time and causing failures, stuck downloads and other issues for users. So we had to switch the logic to use min version of 64 bit CLI.

**Comment by ankitkumarr** [comment]
I see. I thought VS uses the "cli" entry like `"cli": "https://functionscdn.azureedge.net/public/3.0.3233/Azure.Functions.Cli.min.win-x86.3.0.3233.zip"` and not from `standaloneCLI`.

It's weird that we have all full versions in `standaloneCLI` except for win `x64`. But if that's how it works, I guess it's fine.

I think it'd be good to get the full `win-x64` also added to the feed maybe in a different key then. Azure DevOps task for Core Tools today relies on GitHub releases to get the latest core tools version. However, there's several issues there and I am trying to see if we can get them to use this feed as well. If they switch, we'd need to make sure they have access to all the versions through this. I will follow-up with a separate issue then as I move along.

**Comment by soninaren** [comment]
Feed right now is used by more clients than it was designed for. Would need to be careful adding another dependency to it. We are kind of stuck with this change for now. Can definitely add another entry to standalone property for full x64 version.
