### ISSUE TITLE
Question about sort order for v4 feed

### ISSUE THREAD

**Issue by ejizba** [Azure/azure-functions-tooling-feed#238]
Related to https://github.com/Azure/azure-functions-tooling-feed/pull/234

How should we be sorting the .NET runtimes - I assume we should just go with the order in this feed? If so, do we want .NET 5 above .NET 3.1 (essentially making .NET 5 the default) even when it's not LTS? 

cc @ankitkumarr @anthonychu @fiveisprime @phil-allen-msft

**Comment by ankitkumarr** [comment]
I think we'd want .NET 3.1 to be at the top (or the default). Let's change the order in the feed. Wondering if we also need a `default` property there in the list of `dotnet` worker runtimes to be extra sure.

**Comment by ankitkumarr** [comment]
Closing as this was fixed by https://github.com/Azure/azure-functions-tooling-feed/commit/d78ea37d417cd47d16c05f0ee8c01ef16aa3270c
