### ISSUE TITLE
Update tooling feed to add `WEBSITE_USE_PLACEHOLDER_DOTNETISOLATED` by default

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-tooling-feed#480]

**Comment by mattchenderson** [comment]
I staged a coherence check on a branch I created: https://github.com/Azure/azure-functions-tooling-feed/blob/mattchenderson/placeholders/cli-feed-v4.json

I'm not creating a PR for it or anything at this point, but I just wanted to validate an assumption around all this. Possibly serves as the base for a change but we do need to be mindful of incoming automated PRs which may obviate this.

**Comment by mattchenderson** [comment]
Closed by #487
