### ISSUE TITLE
Publishing 8.0 Azure Function App (Linux), deployment failed with BadRequest: AppSetting with name 'WEBSITE_USE_PLACEHOLDER_DOTNETISOLATED ' is not allowed.

### ISSUE THREAD

**Issue by phenning** [Azure/azure-functions-tooling-feed#491]
The following added setting in the feed since 4.61.0 is causing an issue with Publish from Visual Studio

              "WEBSITE_USE_PLACEHOLDER_DOTNETISOLATED ": "1"

REPRO STEPS
1. File > New project > Azure Functions > .NET 8.0 Isolated, leave other options as default (Http trigger)
2. Publish to Azure Function App (Linux)
Plan Type: App service plan

              
![image](https://github.com/Azure/azure-functions-tooling-feed/assets/2433750/00d90a69-8a1f-4b75-9d7d-e033a9aaafbf)
                           
internal bug:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1917518

**Comment by mattchenderson** [comment]
This should now be resolved in the 4.62.0 feed version.

**Comment by phenning** [comment]
Thanks @mattchenderson, I'm working on getting this version as the default feed for 17.9 preview 2 and also backported to 17.8
